### ISSUE TITLE
pandas concatenation does not work, fixed

### ISSUE THREAD

**Issue by georgid** [juanjobosch/SourceFilterContoursMelody#1]
Lines 88-90 of contour_extraction.py (in src.contourExtraction.compute_contour_data) do not work as expected, so I replaced them with 

```
if extra_features is not None:
        sal_features_data = contour_data[headers[0:12]]
        #         frame-by-frame fetures
        frame_by_frame_features_data =  contour_data[headers[12:]]
        dfFeatures = concat([sal_features_data, extra_features], axis=1)
        contour_data = concat([dfFeatures, frame_by_frame_features_data ], axis=1) 
```

**Comment by juanjobosch** [comment]
As commented offline, your proposed code does not actually do what it is expected from this function:
contour_data should not contain frame by frame features, but simply one value, for each feature.
